theme: jekyll-theme-minimal
title: Carl Hellein
description: Personal Github page.

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
      author: "Carl"

  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "pages"

